### PR TITLE
- minor tweak to collavoration tools registry.

### PR DESCRIPTION
**Pull request by sheaphillips**
## Summary
- triggering build / redeploy cycle via PR.

## Notable Changes 
-
-
-

### CODE REVIEW

**Comment by sheaphillips** [comment]
@patricksimonian @jas29 there's something weird happening with ordering of items within topics.  that's the reason for this PR - basically forcing a build/deployment. Hoping we can leave this PR in it's current state for today (haven't run "Cleanup" stage yet - will do this evg). LMK if that disrupts your work/plans.

**Comment by jas29** [comment]
> @patricksimonian @jas29 there's something weird happening with ordering of items within topics. that's the reason for this PR - basically forcing a build/deployment. Hoping we can leave this PR in it's current state for today (haven't run "Cleanup" stage yet - will do this evg). LMK if that disrupts your work/plans.

hey @sheaphillips I didn’t realize this wasn’t working and ran it through the clean up stage as well. You might want to trigger a new build, if you did not want those changes.

**Comment by patricksimonian** [comment]
just add a empty commit @jas29 to restart this process. Get this pr back to cleanup for Shea to deal with. If theres any blockers for you post it here :) 

Lesson learned ? :)

**Comment by patricksimonian** [comment]
Also a reminder this PR __was not approved__ it should not have been cleaned up.

**Comment by sheaphillips** [comment]
no need to rollback at this point.

**Comment by jas29** [comment]
Since we're getting rid of this topic altogether so doesn’t make sense to keep this pr. Closing this branch pr and deleting the branch

**Pull request closed without merging**
