### PR TITLE
add ocp4 service overview to featured content

### PR DESCRIPTION
**Pull request by AndrewJun97**
add ocp4 service overview to featured content

### CODE REVIEW

**Comment by AndrewJun97** [comment]
@deploy-tron deploy web to dev

**Comment by AndrewJun97** [comment]
@deploy-tron deploy web to dev

**Comment by AndrewJun97** [comment]
@deploy-tron deploy web to test

**Review by patricksimonian — APPROVED** [review]

**Comment by AndrewJun97** [comment]
@deploy-tron deploy web to prod

**Comment by AndrewJun97** [comment]
@deploy-tron deploy web to dev

**Pull request merged**
