### PR TITLE
Update registry.yml

### PR DESCRIPTION
**Pull request by orinevares**
## Notable Changes
- added in dropdown MD to show up on devhub

### CODE REVIEW

**Comment by patricksimonian** [comment]
@orinevares can you confirm you have done a `git rebase master` from your adding-dropdown-component branch?

**Comment by patricksimonian** [comment]
you may need to `git checkout master && git pull` prior to that

**Comment by orinevares** [comment]
@patricksimonian have not done that yet but found an old PR that you approved which was not merged. I'll look into it now.

**Comment by patricksimonian** [comment]
let me know if you run into anything !

**Pull request closed without merging**
