### PR TITLE
remove old sso docs

### PR DESCRIPTION
**Pull request by AndrewJun97**
## Summary
Conrad Gustafson reached out asking to remove some documents from the Devhub.

On top of removing the individual sources, I removed the platform-service-migration topic since it would be empty after the documents are removed.

Clipboard - August 10, 2021 10_25 AM

### CODE REVIEW

**Comment by AndrewJun97** [comment]
@deploy-tron deploy web to dev

**Comment by AndrewJun97** [comment]
@deploy-tron deploy web to dev

**Comment by AndrewJun97** [comment]
@deploy-tron deploy web to dev

**Comment by patricksimonian** [comment]
@deploy-tron deploy web to dev

**Pull request closed without merging**
