### PR TITLE
added pathfiner journey

### PR DESCRIPTION
**Pull request by patricksimonian**

### CODE REVIEW

**Comment by patricksimonian** [comment]
@deploy-tron deploy web to dev

**Comment by patricksimonian** [comment]
@MaxWardle https://devhub-app-web-1680-bdec76-dev.apps.silver.devops.gov.bc.ca/

**Comment by MaxWardle** [comment]
@deploy-tron deploy web to dev

**Comment by MaxWardle** [comment]
@deploy-tron deploy web to dev

**Comment by MaxWardle** [comment]
pipeline stuck

**Pull request closed without merging**
