### PR TITLE
Add Platform Services Definition

### PR DESCRIPTION
**Pull request by ShellyXueHan**
## Summary
Add the ref for some Platform Services Definitions

## Notable Changes 
- artifactory
- sysdig
- EDB

### CODE REVIEW

**Review by mitovskaol — APPROVED** [review]

**Review by patricksimonian — APPROVED** [review]

**Comment by patricksimonian** [comment]
@deploy-tron deploy web to dev

**Comment by patricksimonian** [comment]
@deploy-tron deploy web to dev

**Comment by patricksimonian** [comment]
@deploy-tron deploy web to dev

**Comment by patricksimonian** [comment]
@deploy-tron deploy web to test

**Comment by patricksimonian** [comment]
@deploy-tron deploy web to prod

**Pull request merged**
