### PR TITLE
redirect migrated pages to the new content

### PR DESCRIPTION
**Pull request by MonicaG**
## Summary
This is for [DevHub: Improve removed content pages](https://bcdevex.atlassian.net/browse/DEVEXP-82?atlOrigin=eyJpIjoiOTYzMWI2NDhmOGZiNDJjOTgxNWVkNjFkOTczYzI3YjciLCJwIjoiaiJ9)
The task was to redirect the migrated pages to the appropriate pages on the new site.

## Notable Changes

Updated devhubTopic.js to filter webNodes as `n.name === source.name`. 

This change was made because the old comparison (`nodeBelongsToTopic(source.name, n)`) would consider all the topics the node was in. This could lead to duplicates where a url was in multiple topics and used different titles across topics. 

The comparison was not updated in the `nodeBelongsToTopic` method because it is used by the ghNodes. I did not want to alter the filter for that case.

The uniqWith function was changed to use a comparator vs the isEquals functionality. The comparator only compares the url and the title. Duplicates were happening when using isEqual as there were other properties that were different. By using url and title allows for the same url with a different title in a topic.

Besides the redirects the following was also changed:

- Updated Readme.md with "dormant" lifecycle badge
- Updated web/Readme.md with debug/troubleshooting tips
- Update .gitignore to ignore .vscode directory

### CODE REVIEW

**Comment by ty2k** [comment]
@deploy-tron deploy web to dev

**Comment by ty2k** [comment]
@deploy-tron deploy web to dev

**Comment by MonicaG** [comment]
@deploy-tron deploy web to dev

**Comment by MonicaG** [comment]
@deploy-tron deploy web to dev

**Comment by MonicaG** [comment]
@deploy-tron deploy web to dev

**Comment by MonicaG** [comment]
@deploy-tron deploy web to test

**Review by ty2k — APPROVED** [review]
Looks great!

For reference to anyone looking at this in the future, our [failed deployment to dev](https://github.com/bcgov/devhub-app-web/actions/runs/3998540663) was the result of a missing `caddy-s2i-builder` image. To get this image back, we used the BuildConfig for `caddy-s2i-builder` in the `bdec76-tools` namespace to generate a new image.

OpenShift console showing BuildConfigs in the bdec76-tools namespace

**Comment by MonicaG** [comment]
@deploy-tron deploy web to prod

**Pull request merged**
