### PR TITLE
Add support for 'resourceTypes' for Siphon Nodes + updated documentation for Siphon

### PR DESCRIPTION
**Pull request by patricksimonian**
This is an incremental pull request for the source filtering feature

### CODE REVIEW

**Comment by patricksimonian** [comment]
please ignore all Toggle related files, these were pulled in from sprint-5 because of some dependancies I required but otherwise have already been merged and reviewed

**Comment by patricksimonian** [comment]
this was approved by shelly

**Comment by jleach** [comment]
@patricksimonian Consider adding more white space to make the code easier to read; were a few file in here that read like a WoT (Wall of Text). While I think code documentaiton is great and I'm not the best and adding them all the time, I think they're better used to document stuff that's not obvious or anothe way, make sure they're not superfluous. For example, there shouldn't be any need to docuemet what `_.flatMap()` is doing. And finally, that was a pretty big PR. You'll generally get no good feedback on large PRs. Try and keep them under 300 lines of changed code.

```
    // fetch ignore file if exists
    const repoIgnores = await fetchIgnoreFile(repo, owner, token, branch);
```

**Comment by patricksimonian** [comment]
thanks for all of that feedback. I'll definitely try to make the PR's smaller than this one. Also really good point on code readability. I'll take that into account from now on

**Pull request merged**
