### PR TITLE
Add a tile for Andy about Dynamics

### PR DESCRIPTION
**Pull request by ActionAnalytics**
## Summary
Adding a link out to a placeholder document about Microsoft Dynamics 365

## Notable Changes 
- provided link to tagged document

### CODE REVIEW

**Comment by ActionAnalytics** [comment]
@patricksimonian looks like that failed test was on a different file if I'm reading that stack trace correctly

**Comment by patricksimonian** [comment]
taking a look! thanks for the contribution

**Comment by patricksimonian** [comment]
@ActionAnalytics i have rebased this pr and taken over so our henkins will pick this up in the pipeline :)

**Comment by patricksimonian** [comment]
I have verified locally these changes are valid. In addition #1292 addresses the devhub-markdown-verify-test / test action. It is failing because of api throttling. 

The e2e cypress test are also working correctly locally.

**Comment by patricksimonian** [comment]
https://developer.gov.bc.ca/Dynamics-365-FAQ :) :fire:

**Pull request merged**
