### PR TITLE
Update uptime doc ref

### PR DESCRIPTION
**Pull request by ShellyXueHan**
## Summary
uptime.com repo migration (this doc is not included in new doc site yet, we need to discuss if it should)

## Notable Changes 
- ref updated
-
-

### CODE REVIEW

**Comment by ShellyXueHan** [comment]
@deploy-tron help

**Comment by ShellyXueHan** [comment]
@deploy-tron deploy web to dev

**Comment by ty2k** [comment]
Confirmed that the updated reference works to point to the page in `dev`: https://devhub-app-web-1764-bdec76-dev.apps.silver.devops.gov.bc.ca/platform-services-uptime

However, it looks like this update will change the page title and URL because of this leading level 1 heading: https://github.com/bcgov/platform-services-uptime/blob/main/README.md?plain=1#L1

I think it might make sense to either:
- Remove `# platform-services-uptime` from in front of the frontmatter in the new doc to keep the original page title and URL
- Break the new page into a landing README with your new repo title and then a separate documentation page with the current page info

Or maybe it doesn't matter if this page is going to be going away with the new websites? I'm going to approve and leave it up to you!

**Review by ty2k — APPROVED** [review]

**Comment by ShellyXueHan** [comment]
@deploy-tron deploy web to dev

**Review by w8896699 — APPROVED** [review]
Looks good to me

**Comment by ShellyXueHan** [comment]
@ty2k that's fine since we'll be migrating it soon:P As long as the main content is there we are good! thanks for review!

**Comment by ShellyXueHan** [comment]
@deploy-tron deploy web to test

**Comment by ShellyXueHan** [comment]
@deploy-tron deploy web to prod

**Pull request merged**
