### PR TITLE
Add migration instructions and clean up directories

### PR DESCRIPTION
**Pull request by patricksimonian**
## Summary
Quick Summary Here

## Notable Changes 
- added an architecture schematic
- smoothed out installation instructions (that i've tested my self!)
-

### CODE REVIEW

**Comment by patricksimonian** [comment]
@deploy-tron deploy web to dev

**Comment by patricksimonian** [comment]
@deploy-tron deploy web to dev

**Comment by patricksimonian** [comment]
@deploy-tron deploy web to dev

**Comment by patricksimonian** [comment]
@deploy-tron deploy web to dev

**Comment by patricksimonian** [comment]
@deploy-tron deploy web to dev

**Comment by patricksimonian** [comment]
@deploy-tron deploy web to dev

**Comment by patricksimonian** [comment]
@deploy-tron deploy web to test

**Comment by patricksimonian** [comment]
@deploy-tron deploy web to test

**Comment by patricksimonian** [comment]
@deploy-tron deploy web to test

**Comment by patricksimonian** [comment]
@deploy-tron deploy web to prod

**Review by AndrewJun97 — APPROVED** [review]

**Pull request merged**
