### PR TITLE
Content/mobile starter kit

### PR DESCRIPTION
**Pull request by ty2k**
This PR removes the Mobile Signing Service URL from the Mobile Starter Kit topic and replaced it with a link to the ! Signing Changes wiki page. The current link to `https://mss.developer.gov.bc.ca` is not being rendered into a link by DevHub because that site's certificate is expired. (2f6b020382fd1130eed5a9b2dc13be1f8d22dacb)

I've also added a meaningful description to the Mobile Starter Kit topic (e81124928c995765409a2a21a6912bfe0b49054d).

Before (current production):
DevHub production screenshot

After (with the changes in this PR):
DevHub after the changes in this PR

### CODE REVIEW

**Comment by ty2k** [comment]
@deploy-tron deploy web to dev

**Comment by ty2k** [comment]
@deploy-tron deploy web to dev

**Comment by ty2k** [comment]
@deploy-tron deploy web to dev

**Review by ShellyXueHan — APPROVED** [review]
lgtm!

**Comment by ty2k** [comment]
@deploy-tron deploy web to dev

**Comment by ty2k** [comment]
@deploy-tron deploy web to dev

**Comment by ty2k** [comment]
@deploy-tron deploy web to dev

**Comment by ty2k** [comment]
@deploy-tron deploy web to dev

**Comment by ty2k** [comment]
@deploy-tron deploy web to dev

**Comment by ty2k** [comment]
@deploy-tron deploy web to dev

**Comment by ty2k** [comment]
@deploy-tron deploy web to dev

**Comment by ty2k** [comment]
@deploy-tron deploy web to dev

**Comment by ty2k** [comment]
@deploy-tron deploy web to test

**Comment by ty2k** [comment]
@deploy-tron deploy web to prod

**Comment by ty2k** [comment]
In the commit that fixes the build (b3397976844c3e142e9f5d1b7378fbc5500f6356), I've made a change to the `onCreateNode` lifecycle hook that will exclude images from the GitHub CDN (`githubassets.com`). Attempts to pull these [Open Graph images](https://github.blog/2021-06-22-framework-building-open-graph-images/) (GitHub repository preview images) were consistently causing fatal Gatsby build errors due to HTTP 429 responses:

```
 ERROR #11321  PLUGIN

"gatsby-node.js" threw an error while running the onCreateNode lifecycle:

failed to process https://opengraph.githubassets.com/32a41ad6eba8455657addc0178a
3f6b6c027540506a751739190e400321f14cf/bcgov/mobile-signing-service
HTTPError: Response code 429 (Too Many Requests)
```

I've made the decision to simply exclude these images from our DevHub cards in order to fix our broken build chain.

This is how GitHub repository cards with Open Graph images appeared visually prior to this change:
Screen Shot 2022-08-19 at 4 16 13 PM

This is how they will appear going forward, with no Open Graph preview images:
Screen Shot 2022-08-19 at 4 16 17 PM

**Pull request merged**
