### PR TITLE
Edited the documents to take down public cloud resources

### PR DESCRIPTION
**Pull request by abibat-adesina**
## Summary
This PR is to delete public cloud resources

## Notable Changes 
-
-
-

### CODE REVIEW

**Comment by ShellyXueHan** [comment]
@deploy-tron help

**Comment by ShellyXueHan** [comment]
@deploy-tron deploy web to dev

**Comment by ShellyXueHan** [comment]
@deploy-tron configuration

**Comment by MonicaG** [comment]
@deploy-tron deploy web to dev

**Pull request closed without merging**
