### PR TITLE
add community-meetup to events tile

### PR DESCRIPTION
**Pull request by AndrewJun97**
Add community meetup doc to add to the events tile.
Address issue: https://github.com/bcgov/devhub-app-web/issues/1598

### CODE REVIEW

**Review by patricksimonian — APPROVED** [review]

**Comment by AndrewJun97** [comment]
@deploytron deploy web to dev

**Comment by AndrewJun97** [comment]
@deploy-tron deploy web to dev

**Comment by AndrewJun97** [comment]
@deploy-tron deploy web to test

**Comment by AndrewJun97** [comment]
@deply-tron deploy web to prod

**Comment by AndrewJun97** [comment]
@deploy-tron deploy web to prod

**Pull request merged**
