### PR TITLE
Fix typo in web/README.md

### PR DESCRIPTION
**Pull request by ty2k**
## Summary
This PR fixes a typo, but it is mainly here for me to learn the process of deploying a new build of DevHub to OpenShift.

## Notable Changes 
- Fix typo in `./web/README.md`

### CODE REVIEW

**Comment by ty2k** [comment]
@deploy-tron help

**Comment by ty2k** [comment]
@deploy-tron deploy web to dev

**Review by IanKWatts — APPROVED** [review]

**Comment by ty2k** [comment]
@deploy-tron deploy web to dev

**Comment by ty2k** [comment]
@deploy-tron deploy web to test

**Comment by ty2k** [comment]
@deploy-tron deploy web to prod

**Comment by ShellyXueHan** [comment]
@ty2k looks like you've figure things out here! Good job!

**Pull request merged**
