### PR TITLE
Minor proposal on line 62

### PR DESCRIPTION
**Pull request by kant**
## Summary
Minor proposal on line 62.

## Notable Changes 
- There is no notable changes proposed

### CODE REVIEW

**Comment by patricksimonian** [comment]
@kant thanks for making the PR. If at all possible, could you merge all your commits for the other documentation changes into this branch?

**Comment by patricksimonian** [comment]
@kant thanks again for the PR. just poking you again here. In an effort to keep our PR list slim, I'll aim to close these PR's in the next few days. If you see these after its closed I'd encourage you to open up a new PR :) Again thanks 🔥

**Comment by kant** [comment]
I will follow your directives, so, best wishes!

**Comment by patricksimonian** [comment]
> I will follow your directives, so, best wishes!

thanks! and happy new year to you 🔥

**Pull request merged**
