### PR TITLE
add project-resource-quotas

### PR DESCRIPTION
**Pull request by AndrewJun97**
Add project-resource-quotas documentation to developer tools topic

### CODE REVIEW

**Comment by AndrewJun97** [comment]
@deploy-tron deploy web to dev

**Comment by AndrewJun97** [comment]
@deploy-tron deploy web to dev

**Comment by AndrewJun97** [comment]
@deploy-tron deploy web to test

**Review by patricksimonian — APPROVED** [review]

**Comment by AndrewJun97** [comment]
@deploy-tron deploy web to prod

**Pull request merged**
