### PR TITLE
Remove old sso docs

### PR DESCRIPTION
**Pull request by AndrewJun97**
#1641

### CODE REVIEW

**Comment by AndrewJun97** [comment]
@deploy-tron deploy web to dev

**Comment by AndrewJun97** [comment]
@deploy-tron deploy web to dev

**Comment by AndrewJun97** [comment]
@deploy-tron deploy web to test

**Review by patricksimonian — APPROVED** [review]

**Comment by AndrewJun97** [comment]
@deploy-tron deploy web to prod

**Pull request merged**
