### PR TITLE
Update location of API Gateway documentation.

### PR DESCRIPTION
**Pull request by sheaphillips**
## Summary
Per request from team, we are updating the link associated with the API Gateway. 

-
-
-

### CODE REVIEW

**Comment by sheaphillips** [comment]
@deploy-tron help

**Comment by sheaphillips** [comment]
@deploy-tron deploy web to dev

**Review by ty2k — APPROVED** [review]
LGTM 🚀 

Screenshot 2023-06-13 at 3 18 08 PM

**Comment by sheaphillips** [comment]
@deploy-tron deploy web to dev

**Comment by sheaphillips** [comment]
@deploy-tron deploy web to prod

**Comment by sheaphillips** [comment]
@deploy-tron deploy web to staging

**Pull request merged**
