### PR TITLE
Adding rewrite rules 

### PR DESCRIPTION
**Pull request by MonicaG**
## Summary
Added rewrite rules to Caddyfile. I only did two files in order to test if this will work or not.

Also updated topic registry to point to new location of files.

### CODE REVIEW

**Comment by ty2k** [comment]
@deploy-tron deploy web to dev

**Comment by ty2k** [comment]
@deploy-tron configuration

**Comment by ty2k** [comment]
@deploy-tron deploy web to dev

**Comment by ty2k** [comment]
@deploy-tron help

**Comment by ty2k** [comment]
@deploy-tron deploy web to dev

**Comment by w8896699** [comment]
@deploy-tron deploy web to dev

**Comment by w8896699** [comment]
@deploy-tron help

**Comment by w8896699** [comment]
@deploy-tron architecture

**Comment by MonicaG** [comment]
Closing as this was moved to #1794

**Pull request closed without merging**
