### PR TITLE
Update developer-tools.json

### PR DESCRIPTION
**Pull request by mitovskaol**
## Summary
Quick Summary Here

## Notable Changes 
-
-
-

### CODE REVIEW

**Comment by mitovskaol** [comment]
@deploy-tron deploy web to dev

**Comment by mitovskaol** [comment]
@deploy-tron deploy web to prod

**Comment by mitovskaol** [comment]
@deploy-tron deploy web to dev

**Comment by mitovskaol** [comment]
@deploy-tron deploy web to test

**Comment by mitovskaol** [comment]
@deploy-tron deploy web to prod

**Comment by mitovskaol** [comment]
@deploy-tron deploy web to dev

**Review by ShellyXueHan — APPROVED** [review]

**Comment by mitovskaol** [comment]
@deploy-tron deploy web to dev

**Comment by mitovskaol** [comment]
@deploy-tron deploy web to test

**Comment by mitovskaol** [comment]
@deploy-tron deploy web to prod

**Comment by ty2k** [comment]
@ShellyXueHan Should this one be closed without merging? It looks like it is superseded by #1753.

**Comment by ShellyXueHan** [comment]
@deploy-tron deploy web to dev

**Comment by ShellyXueHan** [comment]
@deploy-tron deploy web to test

**Comment by ShellyXueHan** [comment]
@deploy-tron deploy web to test

**Comment by ShellyXueHan** [comment]
@deploy-tron deploy web to test

**Comment by ShellyXueHan** [comment]
@deploy-tron deploy web to prod

**Comment by mitovskaol** [comment]
@deploy-tron deploy web to dev

**Pull request merged**
