### PR TITLE
Doc improvements

### PR DESCRIPTION
**Pull request by patricksimonian**
## Summary
Update readme for silver deployment

### CODE REVIEW

**Comment by patricksimonian** [comment]
@deploy-tron deploy web to dev

**Comment by patricksimonian** [comment]
@deploy-tron deploy web to dev

**Comment by patricksimonian** [comment]
@deploy-tron deploy web to dev

**Comment by patricksimonian** [comment]
@deploy-tron deploy web to dev

**Comment by patricksimonian** [comment]
@deploy-tron deploy web to test

**Comment by patricksimonian** [comment]
@deploy-tron deploy web to prod

**Comment by patricksimonian** [comment]
@deploy-tron deploy web to dev

**Comment by patricksimonian** [comment]
@deploy-tron deploy web to dev

**Comment by patricksimonian** [comment]
@deploy-tron deploy web to dev

**Comment by patricksimonian** [comment]
@deploy-tron deploy web to test

**Comment by patricksimonian** [comment]
@deploy-tron deploy web to prod

**Review by ShellyXueHan — APPROVED** [review]

**Pull request merged**
