### PR TITLE
Bug/471 typography

### LINKED ISSUE #471: Refactor any selective typography styling so that typorgraphy.js base styles are not overridden
It looks like there are specific styles used within headers of several pages that do not reflect the typograhy js settings. 

We will need to explore what headings are being affected and adjust their css so that they are not getting styled by fontsize or font weight

### PR DESCRIPTION
**Pull request by patricksimonian**
## Summary
Removed any header specific styling to allow Typography to do its magic

Fixes #471 

> notes: Not ready for merge!!! #463 needs to be merged and this rebased again off of it. This pr contains that #463 changes since there were major changes to folder structure. This was to prevent merge conflict headaches.

### CODE REVIEW

**Comment by patricksimonian** [comment]
https://devhub-static-dev-478-devhub-dev.pathfinder.gov.bc.ca/

**Comment by patricksimonian** [comment]
@orinevares

**Comment by orinevares** [comment]
Things are still looking inconsistent. Some tags are displaying properly but most are still incorrect. There is also inconsistent tag use. Lets chat through this together when you have the chance.

**Comment by patricksimonian** [comment]
found the source of the issue @orinevares  @sheaphillips if you are interested. 

Typography.js loads its style sheet at the __top__ of the `<head>` by doing a __insert before__ action. The conflicting styles were coming from the bootstrap stylesheets. It didn't matter where you put the stylesheets, typography would always be inserted before and hence the boostrap styles would override.

After digging through the source code i found that you can specifiy an injection location by placing an empty `<style id="typography.js" />` tag in the `<head>`.

**Comment by patricksimonian** [comment]
^^ that message means i resolved that issue

**Comment by orinevares** [comment]
Awesome, thanks Patrick! Is there a new link that would reflect these changes?

**Pull request merged**
